import { test, expect } from '@playwright/test';

test('page editing is discoverable and section links copy without scrolling', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', {configurable: true, value: {writeText: async (text: string) => { (window as any).copiedLink = text; }}}));
  await page.goto('./');
  await expect(page).toHaveTitle(/Vizard/);
  await expect(page.locator('.title-row').getByRole('link', {name: 'Edit this page'})).toBeVisible();
  const link = page.getByRole('link', {name: 'Copy link to Start here', exact: true});
  await link.scrollIntoViewIfNeeded();
  const before = await page.evaluate(() => ({y: scrollY, url: location.href}));
  await page.screenshot({path: '/tmp/vizard-heading-link-desktop.png'});
  await link.click();
  await expect(page.getByRole('status')).toHaveText('Link to Start here copied.');
  expect(await page.evaluate(() => ({y: scrollY, url: location.href}))).toEqual(before);
  expect(await page.evaluate(() => (window as any).copiedLink)).toContain('#start-here');
  await expect(link).toHaveAttribute('data-copy-state', 'success');
  await expect(link.locator('.section-link-feedback')).toHaveText('Link copied');
  await expect(link.locator('.section-link-feedback')).toBeVisible();
  await page.screenshot({path: '/tmp/vizard-doc-controls-desktop.png'});
  await expect(link).not.toHaveAttribute('data-copy-state', 'success');
  await expect(link.locator('.section-link-feedback')).toBeHidden();
  await page.setViewportSize({width: 390, height: 844});
  await page.goto('./');
  await expect(page.locator('.title-row').getByRole('link', {name: 'Edit this page'})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const mobileLink = page.getByRole('link', {name: 'Copy link to Understand the system', exact: true});
  await mobileLink.hover();
  await page.screenshot({path: '/tmp/vizard-heading-link-mobile.png'});
  await mobileLink.click();
  await expect(mobileLink.locator('.section-link-feedback')).toBeVisible();
  await page.screenshot({path: '/tmp/vizard-doc-controls-mobile.png'});
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', {value: {writeText: async () => { throw new Error('Permission denied'); }}}));
  await mobileLink.focus();
  await page.keyboard.press('Enter');
  await expect(mobileLink).toHaveAttribute('data-copy-state', 'error');
  await expect(mobileLink.locator('.section-link-feedback')).toHaveText('Couldn’t copy link');
  await expect(page.getByRole('status')).toContainText('Could not copy');
  expect(errors).toEqual([]);
});
